server:
  port: 8080
spring:
  application:
    name: logback-sample-service
    
eureka:
  instance:
    hostname: localhost  
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  config: classpath:logback.xml
      
logstash:
  host: 127.0.0.1
  port: 5000
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "info"      