spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: docker
---
spring:
  application:
    name: discovery-service  
  config:
    import: optional:configserver:http://localhost:8888