server:
  port: 8080

name:
  value: shopping

spring:
  cloud:
    config:
      override-system-properties: false

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        connectTimeout: 20000
        readTimeout: 20000
  circuitbreaker:
    enabled: true
    
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans