eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
name:
  value: shopping

spring:
  cloud:
    config:
      override-system-properties: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    discovery-client-enabled: true
#    base-url: http://trace-service/
    base-url: http://localhost:9412/

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        connectTimeout: 20000
        readTimeout: 20000
  circuitbreaker:
    enabled: true
    
